# include/BUILD

cc_library(
    name = "sort_headers",
    hdrs = ["sort.hpp"],
    includes = ["."],
    # This makes the target visible to all other packages in your workspace.
    visibility = ["//visibility:public"],
)